version: "3.7"
services:
  db:
    image: "postgres"
    restart: always
    volumes:
      - db:/var/lib/postgresql/data

  es:
    image: "elasticsearch:7.8.0"
    restart: always
    volumes:
      - es:/usr/share/elasticsearch/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - as:/just-cars-api/storage

volumes:
  db:
  es:
  as:
